### ISSUE TITLE
debt: refactor how we handle react-query cache

### ISSUE THREAD

**Issue by EiffelFly** [instill-ai/console#119]
# Context

- When updating cache in react-query, we use code below, this won't retain the order of the old array.

```js
queryClient.setQueryData<Model[]>(["models"], (old) => {
	if (!old) {
		return [newModel];
	}

	return [...old.filter((e) => e.id !== newModel.id), newModel];
});
```

-  Refactor react-query queryKey to make it more reliable, especially model services

**Comment by iamnamananand996** [comment]
Hi @EiffelFly , I am suggesting some solution, please check it once, either this will help or not

To retain the order of the old array when updating the cache in React Query, we can use the `map()` method to update the item that matches the id of the new model and then return the updated array. Here's an example:

**Option 1**.

```
queryClient.setQueryData<Model[]>(["models"], (old) => {
  if (!old) {
    return [newModel];
  }

  return old.map((item) => {
    if (item.id === newModel.id) {
      return newModel;
    }
    return item;
  });
});
```


and if the new model is not already present in the old array, the above code will not add it to the end of the array. 
If we want to add the new model to the end of the array, we can use the `concat()` method instead of `map()`, like this:

**Option 2**
```
queryClient.setQueryData<Model[]>(["models"], (old) => {
  if (!old) {
    return [newModel];
  }

  return old.filter((item) => item.id !== newModel.id).concat(newModel);
});
```
This code first filters out the item with the same id as the new model, and then uses `concat()` to add the new model to the end of the array. Again, this ensures that the order of the old array is retained even after the update.

**Option 3**.

```
const itemIndex = old.findIndex((item) => item.id === newModel.id);
if (itemIndex > -1) {
  const newArray = [...old];
  newArray.splice(itemIndex, 1, newModel);
  return newArray;
} else {
  return [...old, newModel];
}
```

By using `splice()` to replace the item at a specific index, this code ensures that the order of the array is maintained, even after updating the cache.
